apiVersion: eksctl.io/v1alpha5

kind: ClusterConfig

metadata:
  name: vedant-cluster
  region: ap-south-1
  tags:
    creator: vedant

nodeGroups:
  - name: v1service
    instanceType: t2.micro
    amiFamily: Ubuntu2204   # need to check
    instancePrefix: "v1service" # v1service-vedant-cluster-v1service-Node
    desiredCapacity: 1
    minSize: 1
    maxSize: 1
    tags:
      environment: prod
      app: v1
    labels:
      environment: prod
      app: v1

  - name: v2service
    instanceType: t2.micro
    amiFamily: Ubuntu2204   # need to check
    instancePrefix: "v2service" # need to check
    desiredCapacity: 1
    minSize: 1
    maxSize: 1
    tags:
      environment: prod
      app: v2
    labels:
      environment: prod
      app: v2

