apiVersion: networking.k8s.io/v1

kind: Ingress

metadata:
  name: avni-ingress

spec:
  ingressClassName: nginx
  rules:
    - host: "/"    # give host name
      http:
        paths:
          - pathType: Prefix
            path: /v1
            backend:
              service:
                name: v1-service
                port:
                  number: 8088       # service port no
    - host: "/"    # give host name
      http:
        paths:
          - pathType: Prefix
            path: /v2
            backend:
              service:
                name: v2-service
                port:
                  number: 8088       # service port no
